apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: kubedevnews
  POSTGRES_USER: kubedevnews
  POSTGRES_PASSWORD: Pg#123
  DB_DATABASE: kubedevnews
  DB_USERNAME: kubedevnews
  DB_PASSWORD: Pg#123
  DB_SSL_REQUIRE: "false"
